-- @Name: index-data
-- @Depends: query-data-b index-schema
-- @Flags: index 
-- @Description: Index on large tables
-- @Score: 8

USE DATASET;


SELECT LINEITEM.L_PARTKEY, LINEITEM.L_SUPPKEY, LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER, LINEITEM.L_COMMENT FROM LINEITEM WHERE LINEITEM.L_PARTKEY < 10 AND LINEITEM.L_COMMENT >= 'y';
SELECT LINEITEM.L_PARTKEY, LINEITEM.L_SUPPKEY, LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER, LINEITEM.L_COMMENT FROM LINEITEM WHERE LINEITEM.L_PARTKEY < 20 AND LINEITEM.L_COMMENT >= 'y';
SELECT LINEITEM.L_PARTKEY, LINEITEM.L_SUPPKEY, LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER, LINEITEM.L_COMMENT FROM LINEITEM WHERE LINEITEM.L_PARTKEY < 10 AND LINEITEM.L_COMMENT >= 'x';
SELECT LINEITEM.L_PARTKEY, LINEITEM.L_SUPPKEY, LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER, LINEITEM.L_COMMENT FROM LINEITEM WHERE LINEITEM.L_PARTKEY < 100 AND LINEITEM.L_PARTKEY >= 80 AND LINEITEM.L_COMMENT <= 'c';
SELECT LINEITEM.L_PARTKEY, LINEITEM.L_SUPPKEY, LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER, LINEITEM.L_COMMENT FROM LINEITEM WHERE LINEITEM.L_PARTKEY < 10 AND LINEITEM.L_COMMENT <= 'b';


-- Note: our dataset contain only partial data from TPCH
INSERT INTO ORDERS VALUES (10, 100, 'F', 1234.5, '3-MDEIUM', 'Clerk#000000001', 0, 'nothing here'), (11, 101, 'F', 1234.5, '3-MDEIUM', 'Clerk#000000002', 0, 'nothing there'), (12, 102, 'F', 2234.5, '3-MDEIUM', 'Clerk#000000003', 0, 'still nothing'), (330, 303, 'O', 12346.5, '3-MDEIUM', 'Clerk#000000023', 0, 'nothing!'), (451000, 3246, 'F', 98765.5, '3-MDEIUM', 'Clerk#000003453', 0, 'wow');

SELECT * FROM ORDERS WHERE O_ORDERKEY > 5 AND O_ORDERKEY < 50;
SELECT * FROM ORDERS WHERE O_ORDERKEY >= 450900 AND O_ORDERKEY <= 451111;
SELECT * FROM ORDERS WHERE O_ORDERKEY = 123456;

-- Note: if you didn't create implict index for foreign key, it may take much time (but shuoldn't be more than minutes)
DELETE FROM LINEITEM WHERE L_ORDERKEY >= 450950 AND L_ORDERKEY < 451050;

DELETE FROM ORDERS WHERE O_ORDERKEY = 451010;
SELECT * FROM ORDERS WHERE O_ORDERKEY > 450990 AND O_ORDERKEY <= 451010;
DELETE FROM ORDERS WHERE O_ORDERKEY > 450950 AND O_ORDERKEY < 451050;
SELECT * FROM ORDERS WHERE O_ORDERKEY >= 450900 AND O_ORDERKEY <= 451100;
