-- @Name: multi-join
-- @Depends: optional
-- @Flags: mj
-- @Description: Index on large tables
-- @Score: 8

USE DATASET;

-- Table size is meaningless here becasue predicate pushdown is needed
-- Check 3 tables join
SELECT SUPPLIER.S_NAME, NATION.N_NAME, REGION.R_NAME FROM SUPPLIER, NATION, REGION WHERE SUPPLIER.S_NATIONKEY = NATION.N_NATIONKEY  AND NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'AFRICA';

-- Check 4 tables join
SELECT PARTSUPP.PS_AVAILQTY, SUPPLIER.S_SUPPKEY, NATION.N_NAME FROM PARTSUPP, SUPPLIER, NATION, REGION WHERE PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY AND SUPPLIER.S_NATIONKEY = NATION.N_NATIONKEY AND NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'AFRICA' AND SUPPLIER.S_ACCTBAL < -888;

-- Check 5 tables join
SELECT LINEITEM.L_ORDERKEY, LINEITEM.L_QUANTITY, LINEITEM.L_TAX, PARTSUPP.PS_SUPPLYCOST FROM LINEITEM, PARTSUPP, SUPPLIER, NATION, REGION WHERE LINEITEM.L_SUPPKEY = PARTSUPP.PS_SUPPKEY AND LINEITEM.L_PARTKEY = PARTSUPP.PS_PARTKEY AND PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY AND SUPPLIER.S_NATIONKEY = NATION.N_NATIONKEY AND NATION.N_REGIONKEY = REGION.R_REGIONKEY AND REGION.R_NAME = 'ASIA' AND PARTSUPP.PS_SUPPLYCOST < 10.1 AND LINEITEM.L_QUANTITY <= 10.1 AND PARTSUPP.PS_SUPPLYCOST > 5.1;
