-- @Name: query-nest
-- @Depends: optional
-- @Flags: nest
-- @Description: Nest subquery
-- @Score: 2
USE DATASET;

SELECT NATION.N_NATIONKEY, NATION.N_NAME FROM NATION WHERE NATION.N_REGIONKEY = (SELECT REGION.R_REGIONKEY FROM REGION WHERE REGION.R_NAME = 'ASIA') AND NATION.N_NATIONKEY < 1000;


-- Check deep recursive query
SELECT COUNT(*) FROM PARTSUPP WHERE PARTSUPP.PS_SUPPKEY IN (SELECT SUPPLIER.S_SUPPKEY FROM SUPPLIER WHERE SUPPLIER.S_NATIONKEY IN (SELECT NATION.N_NATIONKEY FROM NATION WHERE NATION.N_REGIONKEY IN (SELECT REGION.R_REGIONKEY FROM REGION WHERE REGION.R_NAME = 'ASIA')));
