-- @Name: query-order
-- @Depends: optional
-- @Flags: order
-- @Description: Ordered query for pagination
-- @Score: 2

SELECT LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER FROM LINEITEM WHERE LINEITEM.L_ORDERKEY < 10 LIMIT 10;
SELECT LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER FROM LINEITEM WHERE LINEITEM.L_ORDERKEY < 10 LIMIT 10 OFFSET 10;
SELECT LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER FROM LINEITEM WHERE LINEITEM.L_ORDERKEY < 10 LIMIT 10 OFFSET 20;
SELECT LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER FROM LINEITEM WHERE LINEITEM.L_ORDERKEY < 10 LIMIT 10 OFFSET 30;

