-- @Name: query-group
-- @Depends: optional
-- @Flags: group
-- @Description: Group query
-- @Score: 1
USE DATASET;


SELECT C_MKTSEGMENT, COUNT(*), MAX(C_ACCTBAL)  FROM CUSTOMER GROUP BY C_MKTSEGMENT;

SELECT REGION.R_NAME, COUNT(*)  FROM NATION, REGION WHERE REGION.R_REGIONKEY = NATION.N_REGIONKEY  GROUP BY NATION.N_REGIONKEY;

