-- @Name: query-fuzzy
-- @Depends: optional
-- @Flags: group
-- @Description: Fuzzy query
-- @Score: 1
USE DATASET;

SELECT N_NAME FROM NATION WHERE N_NAME LIKE 'A%A';
SELECT N_NAME FROM NATION WHERE N_NAME LIKE 'IRA_';
SELECT N_NAME FROM NATION WHERE N_NAME LIKE 'R____A';
SELECT N_NAME FROM NATION WHERE N_NAME LIKE 'UNITED %';
SELECT N_NAME FROM NATION WHERE N_NAME LIKE '____A';
SELECT N_NAME FROM NATION WHERE N_NAME LIKE '_R%A%';

SELECT C_NAME, C_ACCTBAL FROM CUSTOMER WHERE CUSTOMER.C_NAME LIKE '%#00%123_';

