-- @Name: query-nest
-- @Depends: optional
-- @Flags: nest
-- @Description: Nest subquery
-- @Score: 2
USE DATASET;

SELECT N_NATIONKEY, N_NAME FROM NATION WHERE N_REGIONKEY = (SELECT R_REGIONKEY FROM REGION WHERE R_NAME = 'ASIA') AND N_NATIONKEY < 1000;


-- Check deep recursive query
SELECT COUNT(*) FROM PARTSUPP WHERE PS_SUPPKEY IN (SELECT S_SUPPKEY FROM SUPPLIER WHERE S_NATIONKEY IN (SELECT N_NATIONKEY FROM NATION WHERE N_REGIONKEY IN (SELECT R_REGIONKEY FROM REGION WHERE R_NAME = 'ASIA')));
