-- @Name: table
-- @Depends: system
-- @Flags: 
-- @Description: Check basic table-level operation
-- @Score: 7

USE DB;

-- Check simple table creation
-- Notice: table TBL* will be used in feature
CREATE TABLE TBL (a INT NOT NULL, b VARCHAR(16) NOT NULL, c FLOAT NOT NULL);
CREATE TABLE TBL2 (a INT NOT NULL, b VARCHAR(17) NOT NULL, c FLOAT NOT NULL);
CREATE TABLE TBL3 (a INT NOT NULL, b VARCHAR(18) NOT NULL, c FLOAT NOT NULL);
CREATE TABLE TBL4 (a INT NOT NULL, b VARCHAR(19) NOT NULL, c FLOAT NOT NULL);
CREATE TABLE TBL5 (a INT NOT NULL, b VARCHAR(20) NOT NULL, c FLOAT NOT NULL);
CREATE TABLE TBL6 (a INT NOT NULL, b VARCHAR(15) NOT NULL, c FLOAT NOT NULL);
CREATE TABLE TBL7 (a INT NOT NULL, b VARCHAR(14) NOT NULL, c FLOAT NOT NULL);
CREATE TABLE TBL8 (a INT NOT NULL, b VARCHAR(13) NOT NULL, c FLOAT NOT NULL);
CREATE TABLE TBL9 (a INT NOT NULL, b VARCHAR(12) NOT NULL, c FLOAT NOT NULL);
CREATE TABLE TBL10 (a INT NOT NULL, b VARCHAR(11) NOT NULL, c FLOAT NOT NULL);
SHOW TABLES;
DESC TBL;


-- Check drop table 
DROP TABLE TBL5;
DROP TABLE TBL10;
SHOW TABLES;


