-- @Name: query-data-a
-- @Depends: data
-- @Flags: query
-- @Description: large table query
-- @Score: 3

USE DATASET;

SELECT * FROM REGION;
SELECT * FROM REGION WHERE REGION.R_REGIONKEY = 1;
SELECT R_REGIONKEY FROM REGION WHERE REGION.R_REGIONKEY < 3 AND REGION.R_REGIONKEY > 1;
SELECT R_REGIONKEY FROM REGION WHERE REGION.R_REGIONKEY < 6 AND REGION.R_REGIONKEY > 1 AND REGION.R_NAME = 'AMERICA';
SELECT S_SUPPKEY, S_ACCTBAL FROM SUPPLIER WHERE SUPPLIER.S_ACCTBAL <= -963.2;
-- Note: it triggers a full-table scan
SELECT L_PARTKEY, L_SUPPKEY, L_ORDERKEY, L_LINENUMBER, L_COMMENT FROM LINEITEM WHERE LINEITEM.L_QUANTITY > 5.1 AND LINEITEM.L_QUANTITY < 7.2 AND LINEITEM.L_COMMENT >= 'z';



