-- @Name: query-data-1
-- @Depends: data
-- @Flags: query
-- @Description: large table query
-- @Score: 3

USE DATASET;

SELECT * FROM REGION WHERE REGION.R_REGIONKEY >= 0;
SELECT REGION.R_REGIONKEY FROM REGION WHERE REGION.R_REGIONKEY < 3 AND REGION.R_REGIONKEY > 1;
SELECT REGION.R_REGIONKEY FROM REGION WHERE REGION.R_REGIONKEY < 6 AND REGION.R_REGIONKEY > 1 AND REGION.R_NAME = 'AMERICA';
SELECT SUPPLIER.S_SUPPKEY, SUPPLIER.S_ACCTBAL FROM SUPPLIER WHERE SUPPLIER.S_ACCTBAL <= -963.2;
SELECT LINEITEM.L_PARTKEY, LINEITEM.L_SUPPKEY, LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER, LINEITEM.L_COMMENT FROM LINEITEM WHERE LINEITEM.L_SUPPKEY < 10 AND LINEITEM.L_COMMENT >= 'z';


