-- @Name: fk-schema
-- @Depends: pk
-- @Flags: fk
-- @Description: Schema alter for foreign keys
-- @Score: 1

USE DB2;
CREATE TABLE TX (ID INT, VALUE INT, PRIMARY KEY (ID));


CREATE TABLE TY (ID INT, ID_TX INT, VALUE INT);

INSERT INTO TX VALUES (1, 1), (2, 2), (3, 3), (4, 4);
INSERT INTO TY VALUES (1, 1, 1), (2, 2, 2), (3, 6, 9);

-- failed because (3, 6, 9)
ALTER TABLE TY ADD CONSTRAINT FK_ID_TX FOREIGN KEY (ID_TX) REFERENCES TX(ID);
DELETE FROM TY WHERE VALUE > 5;
ALTER TABLE TY ADD CONSTRAINT FK_ID_TX FOREIGN KEY (ID_TX) REFERENCES TX(ID);
DESC TY;


INSERT INTO TY VALUES (4, 8, 12);
DELETE FROM TX WHERE ID = 1;
ALTER TABLE TY DROP FOREIGN KEY FK_ID_TX;
DELETE FROM TX WHERE ID = 1;
INSERT INTO TY VALUES (4, 8, 12);
SELECT * FROM TX;
SELECT * FROM TY;
DESC TY;
